# Generated by Django 5.0 on 2024-05-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="S",
                        help_text="Se o registro está ativo ou não",
                        max_length=1,
                        verbose_name="ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Data da criação do registro",
                        verbose_name="data de criação",
                    ),
                ),
                (
                    "hora_criacao",
                    models.TimeField(
                        auto_now_add=True,
                        help_text="Hora da criação do registro",
                        verbose_name="hora de criação",
                    ),
                ),
                (
                    "data_ultima_alteracao",
                    models.DateField(
                        auto_now=True,
                        help_text="Data da última alteração",
                        verbose_name="data da última alteração",
                    ),
                ),
                (
                    "hora_ultima_alteracao",
                    models.TimeField(
                        auto_now=True,
                        help_text="Hora da última alteração",
                        verbose_name="hora da última alteração",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Nome padronizado do código",
                        max_length=125,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Descrição da utilidade dessa configuração",
                        max_length=350,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="Valor da configuração",
                        max_length=50,
                        verbose_name="valor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "db_table": "configuracao",
                "ordering": ["-id"],
            },
        ),
    ]
